export const FETCH_VALUE_BEGIN = 'FETCH_VALUE_BEGIN';
export type FETCH_VALUE_BEGIN = typeof FETCH_VALUE_BEGIN;

export const FETCH_VALUE_SUCCESS = 'FETCH_VALUE_SUCCESS';
export type FETCH_VALUE_SUCCESS = typeof FETCH_VALUE_SUCCESS;

export const FETCH_VALUE_ERROR = 'FETCH_VALUE_ERROR';
export type FETCH_VALUE_ERROR = typeof FETCH_VALUE_ERROR;
